/*
 * ARM Limited (ARM) is supplying this software for use with Cortex-M
 * processor based microcontroller, but can be equally used for other
 * suitable processor architectures. This file can be freely distributed.
 * Modifications to this file shall be clearly marked.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS". NO WARRANTIES, WHETHER EXPRESS, IMPLIED
 * OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.
 * ARM SHALL NOT, IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @file     irq.h
 * @brief    CMSIS HeaderFile
 * @version  1.2
 * @date     02. June 2017
 * @note     Generated by SVDConv V3.3.9 on Friday, 02.06.2017 20:26:27
 *           from File 'Cleveland2.svd',
 *           last modified on Friday, 02.06.2017 12:25:41
 */



/** @addtogroup Mstarsemi
  * @{
  */


/** @addtogroup Cleveland
  * @{
  */


#ifndef IRQ_H
#define IRQ_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup Configuration_of_CMSIS
  * @{
  */



/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */

typedef enum {
/* =======================================  ARM Cortex-M4 Specific Interrupt Numbers  ======================================== */
  Reset_IRQn                = -15,              /*!< -15  Reset Vector, invoked on Power up and warm reset                     */
  NonMaskableInt_IRQn       = -14,              /*!< -14  Non maskable Interrupt, cannot be stopped or preempted               */
  HardFault_IRQn            = -13,              /*!< -13  Hard Fault, all classes of Fault                                     */
  MemoryManagement_IRQn     = -12,              /*!< -12  Memory Management, MPU mismatch, including Access Violation
                                                     and No Match                                                              */
  BusFault_IRQn             = -11,              /*!< -11  Bus Fault, Pre-Fetch-, Memory Access Fault, other address/memory
                                                     related Fault                                                             */
  UsageFault_IRQn           = -10,              /*!< -10  Usage Fault, i.e. Undef Instruction, Illegal State Transition        */
  SVCall_IRQn               =  -5,              /*!< -5 System Service Call via SVC instruction                                */
  DebugMonitor_IRQn         =  -4,              /*!< -4 Debug Monitor                                                          */
  PendSV_IRQn               =  -2,              /*!< -2 Pendable request for system service                                    */
  SysTick_IRQn              =  -1,              /*!< -1 System Tick Timer                                                      */
/* =========================================  Cleveland Specific Interrupt Numbers  ========================================== */
  PM_GPIO0_IRQn             =  118,              /*!< 118 PM GPIO0                                                             */
  PM_GPIO1_IRQn             =  119,              /*!< 118 PM GPIO1                                                             */
  PM_GPIO2_IRQn             =  120,              /*!< 118 PM GPIO2                                                             */
  PM_GPIO3_IRQn             =  121,              /*!< 118 PM GPIO3                                                             */
  PM_GPIO4_IRQn             =  122,              /*!< 118 PM GPIO4                                                             */
  PM_GPIO5_IRQn             =  123,              /*!< 118 PM GPIO5                                                             */
  PM_GPIO6_IRQn             =  124,              /*!< 118 PM GPIO6                                                             */
  PM_GPIO7_IRQn             =  125,              /*!< 118 PM GPIO7                                                             */
  PM_GPIO8_IRQn             =  126,              /*!< 118 PM GPIO8                                                             */
  PM_GPIO9_IRQn             =  127,              /*!< 118 PM GPIO9                                                             */
  PM_GPIO10_IRQn            =  128,              /*!< 118 PM GPIO10                                                            */
  PM_GPIO11_IRQn            =  129,              /*!< 118 PM GPIO11                                                            */
  PM_GPIO12_IRQn            =  130,              /*!< 118 PM GPIO12                                                            */

  WDT_IRQn                  =  96,              /*!< 0  WDT                                                                    */
  TIMER0_IRQn               =  81,              /*!< 1  TIMER0                                                                 */
  TIMER1_IRQn               =  82,              /*!< 2  TIMER1                                                                 */
  TIMER2_IRQn               =  83,              /*!< 3  TIMER2                                                                 */
  TIMER3_IRQn               =  84,              /*!< 4  TIMER3                                                                 */
  TIMER4_IRQn               =  85,              /*!< 5  TIMER4                                                                 */
  UART0_IRQn                =  32,              /*!< 16 UART0                                                                  */
  UART1_IRQn                =  33,              /*!< 17 UART1                                                                  */
  UART2_IRQn                =  34,              /*!< 18 UART2                                                                  */
  BDMA_IRQn                 =  38,              /*!< 22 BDMA                                                                   */
  VBDMA_IRQn                =  39,              /*!< 23 V_BDMA                                                                 */
  AUDIO_IRQn                =  54,              /*!< 38 Audio                                                                  */
  AUDIO_GEN_IRQn            =  55,              /*!< 39 Audio Gen                                                              */
  AUDIO_VAD_IRQn            =  74,              /*!< 58 Audio Gen                                                              */
  HK0ToCP_IRQn              =  44,            //reg_hst1to0_int
  HK1ToCP_IRQn              =  42,            //reg_hst2to0_int/
  CPToHK0_IRQn              =  46,            //reg_hst0to1_int/
  MAX_IRQn                  = 239,
  NONE_IRQn                 = 0xFFFF,
  NOPMIRQ_IRQn              = NONE_IRQn,
  NOPMFIQ_IRQn              = NONE_IRQn,


} IRQn_Type;



/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

/* ===========================  Configuration of the ARM Cortex-M4 Processor and Core Peripherals  =========================== */
#define __CM4_REV                 0x0100U       /*!< CM4 Core Revision                                                         */
#define __NVIC_PRIO_BITS               3        /*!< Number of Bits used for Priority Levels                                   */
#define __Vendor_SysTickConfig         0        /*!< Set to 1 if different SysTick Config is used                              */
#define __MPU_PRESENT                  1        /*!< MPU present or not                                                        */
#define __FPU_PRESENT                  1        /*!< FPU present or not                                                        */


/** @} */ /* End of group Configuration_of_CMSIS */

#include "core_cm4.h"                           /*!< ARM Cortex-M4 processor and core peripherals                              */
//#include "system_Cleveland.h"                   /*!< Cleveland System                                                          */



#ifdef __cplusplus
}
#endif

#endif /* IRQ_H */


/** @} */ /* End of group Murphy */

/** @} */ /* End of group Mstarsemi */
